apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow-templates
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/app-definitions/argo-workflow-templates
    repoURL: https://github.com/thegalah/homeserver
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
