apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/thegalah/homeserver
    targetRevision: master
    path: argocd/app-definitions/cert-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
