apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root-app
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: argocd/managed-apps
    repoURL: "https://github.com/thegalah/homeserver"
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
